# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(default=0)),
                ('ws_type', models.CharField(choices=[(0, 'Office'), (1, 'Shopping'), (2, 'Home')], max_length=1)),
                ('description', models.CharField(max_length=8000)),
                ('price', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(verbose_name='start of sharing')),
                ('end_date', models.DateTimeField(verbose_name='end of sharing')),
                ('register_date', models.DateTimeField(verbose_name='register this ws in the system')),
                ('expire_date', models.DateTimeField(verbose_name='when advertising of this ws ends')),
                ('published', models.BooleanField(verbose_name='is published?')),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('map_location', models.CharField(help_text='Longitude, Latitude', max_length=200)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsa.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='when comment is created')),
                ('published', models.BooleanField(verbose_name='is published?')),
                ('ip', models.CharField(max_length=40)),
                ('spam', models.BooleanField(verbose_name='is it spam?')),
                ('commenter_email', models.CharField(max_length=80)),
                ('commenter_name', models.CharField(max_length=80)),
                ('comment', models.CharField(max_length=8000)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsa.UserProfile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsa.Workspace')),
            ],
        ),
    ]
