# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpsa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkspaceComment',
            new_name='Comment',
        ),
    ]
