# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsa', '0002_auto_20160214_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='ws_type',
            field=models.IntegerField(choices=[(0, 'Office'), (1, 'Shopping'), (2, 'Home')]),
        ),
    ]
