# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpsa', '0003_auto_20160214_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workspace',
            new_name='Workplace',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='workspace',
            new_name='workplace',
        ),
    ]
