# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpsa', '0004_auto_20160214_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
