# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsa', '0005_auto_20160215_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
