# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsa', '0007_auto_20160307_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
