# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsa', '0008_auto_20160628_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
